### ISSUE TITLE
PromQL doesn't use labels included in the query

### ISSUE THREAD

**Issue by jhuizingh** [kedify/otel-add-on#46]
I like the idea of this addon and was trying to test it out. I can not get it to work as I would expect.  I already have various OTEL collectors that I would work it in with so I don't need to install a separate one via the helm chart. 

Here is what I have done:

I installed the helm chart in the `observability` namespace. 
`v0.0.4` helm values:

```
---
opentelemetry-collector:
  enabled: false
```

The relevant part of my OTEL collector is that it uses prometheus to scrape a kube state metrics installation: 

```

mode: deployment
...  condensed ... 
config:
  receivers:

...  condensed ... 
    prometheus/kube_state_metrics:
      config:
        scrape_configs:
          - job_name: kube-state-metrics
            scrape_interval: ${OTEL_DEFAULT_SCRAPE_INTERVAL}
            static_configs:
              - targets:
                  - kube-state-metrics.observability.svc:8080

...  condensed ... 
    k8sattributes/kube_state_metrics:
        pod_association:
          - sources:
            - from: resource_attribute
              name: k8s.pod.uid
          - sources:
            - from: resource_attribute
              name: k8s.pod.name
            - from: resource_attribute
              name: k8s.namespace.name
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.deployment.name
            - k8s.statefulset.name
            - k8s.daemonset.name
            - k8s.cronjob.name
            - k8s.job.name
            - k8s.node.name
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.pod.start_time
    groupbyattrs:
      keys:
        - k8s.pod.name
        - k8s.namespace.name
  exporters:
    otlp/kedify:
      endpoint: keda-otel-scaler.observability.svc:4317
      compression: none
      tls:
        insecure: true
  service:
...  condensed ... 
      metrics/kube_state_metrics:
        receivers:
          - prometheus/kube_state_metrics
        processors:
          - memory_limiter
...  condensed ... 
          - k8sattributes/kube_state_metrics
          - batch
        exporters:
          - otlp/kedify
```

     

With the service installed and running, I tried to create a simple test scenarion. I wanted to create two deployments, a leader and a follower, and manually change the replicas of the leader and see the follower adjust to match it.  I used the following to try and achieve that.

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kedify-scale-leader
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
    spec:
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kedify-scale-follower
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
    spec:
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.2
---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: otel-example
  namespace: observability
spec:
  scaleTargetRef:
    name: kedify-scale-follower
  minReplicaCount: 0
  maxReplicaCount: 10

  triggers:
    - type: external
      metadata:
        scalerAddress: "keda-otel-scaler.observability.svc:4318"
#        scalerAddress: "host.k3d.internal:4318"

        # required - no default
        # PromQL-like query identifying exactly one metric name
        # if metric has more dimensions, these can be further specified by labels {a=b,c=2..}
        # when multiple time series (/dimensions) fulfil the label selector, then we first apply the operationOverTime
        # on each time serie and combine the result with the optional operation that's part of this query (if omitted, it's sum)
        #
        # grammar:
        # op(metricName{label1=val1, label2=val2})  , where 'op' is one of {sum, min, max, avg}
        #
        # examples:
        #  - avg(http_requests_total{code=200,handler=targets,instance=example:8080,method=get})   (good with operationOverTime=rate)
        #  - up{instance=prod:8080}
        #  - foobar
        #
        # caveats:
        #  - label selector do not support advanced operators like != or =~ (only simple = denoting exact match is supported atm.)
        #  - it's not supported to combine different metric names here
        #  - no arithmetic
        metricQuery: kube_deployment_status_replicas_available{k8s_namespace_name="observability", k8s_deployment_name="kedify-scale-leader"}

        targetValue: "1"

        # optional - default no limit
        # lower integer bound for the value calculated by the scaler (~min replicas)
        clampMin: "0"

        # optional - default no limit
        # upper integer bound for the value calculated by the scaler (~max replicas)
        clampMax: "10"

        # optional - default 'last_one', available values:
        #    example metric   t1   t2   t3   t4   t5   t6   t7        result
        #   - last_one  ...   3    2    1    6    3    2    3    ->   3
        #   - min       ...   3    2    1    6    3    2    3    ->   1
        #   - max       ...   3    2    1    6    3    2    3    ->   6
        #   - avg       ...   3    2    1    6    3    2    3    ->   round(20/7)=7
        #   - rate      ...   1    2    3    4    5    6    7    ->   1 (provided, measurements were taken each second)
        #   - count     ...   3    2    1    6    3    2    3    ->   7
        # operationOverTime: "rate"
        operationOverTime: last_one
  # for faster reaction - debug
  # advanced:
  #   horizontalPodAutoscalerConfig:
  #     behavior:
  #       scaleDown:
  #         stabilizationWindowSeconds: 10
  #       scaleUp:
  #         stabilizationWindowSeconds: 10
```
I tried `type: kedify-otel` but there was an error that it was an unknown type. 

Everything is hooked up, but the metric query isn't working correctly.  Here are the logs from the otel-add-on-scaler pod:

```
kubectl logs -n observability otel-add-on-scaler-775656bb5-84zcs |tail
01-10 21:35:12  INFO    GetMetrics      got metric value:       {"name": "kube_deployment_status_replicas_available", "labels": {"k8s_deployment_name":"kedify-scale-leader","k8s_namespace_name":"observability"}, "value": 122, "found": true, "error": null}
01-10 21:35:12  INFO    GetMetrics      got metric value:       {"name": "kube_deployment_status_replicas_available", "labels": {"k8s_deployment_name":"kedify-scale-leader","k8s_namespace_name":"observability"}, "value": 122, "found": true, "error": null}
01-10 21:35:12  INFO    GetMetrics      got metric value:       {"name": "kube_deployment_status_replicas_available", "labels": {"k8s_deployment_name":"kedify-scale-leader","k8s_namespace_name":"observability"}, "value": 122, "found": true, "error": null}
01-10 21:35:12  INFO    GetMetrics      got metric value:       {"name": "kube_deployment_status_replicas_available", "labels": {"k8s_deployment_name":"kedify-scale-leader","k8s_namespace_name":"observability"}, "value": 122, "found": true, "error": null}
01-10 21:35:27  INFO    GetMetrics      got metric value:       {"name": "kube_deployment_status_replicas_available", "labels": {"k8s_deployment_name":"kedify-scale-leader","k8s_namespace_name":"observability"}, "value": 122, "found": true, "error": null}
01-10 21:35:27  INFO    GetMetrics      got metric value:       {"name": "kube_deployment_status_replicas_available", "labels": {"k8s_deployment_name":"kedify-scale-leader","k8s_namespace_name":"observability"}, "value": 122, "found": true, "error": null}
01-10 21:35:42  INFO    GetMetrics      got metric value:       {"name": "kube_deployment_status_replicas_available", "labels": {"k8s_deployment_name":"kedify-scale-leader","k8s_namespace_name":"observability"}, "value": 122, "found": true, "error": null}
01-10 21:35:42  INFO    GetMetrics      got metric value:       {"name": "kube_deployment_status_replicas_available", "labels": {"k8s_deployment_name":"kedify-scale-leader","k8s_namespace_name":"observability"}, "value": 122, "found": true, "error": null}
01-10 21:35:42  INFO    GetMetrics      got metric value:       {"name": "kube_deployment_status_replicas_available", "labels": {"k8s_deployment_name":"kedify-scale-leader","k8s_namespace_name":"observability"}, "value": 122, "found": true, "error": null}
01-10 21:35:42  INFO    GetMetrics      got metric value:       {"name": "kube_deployment_status_replicas_available", "labels": {"k8s_deployment_name":"kedify-scale-leader","k8s_namespace_name":"observability"}, "value": 122, "found": true, "error": null}

```

Even with the `leader` deployment at `1` replica, it gets `122` as the count. I determined that 122 is actually the count of all pods running in the cluster. It is not respecting the labels at all with that query. There is only 1 deployment with the label `k8s_deployment_name: kedify-scale-leader` and it has a value of 1 if I look in Grafana through my normal backend.  However, `kedify-scale-follower` is automatically scaling up to 10 (the max) as it tries to get to `122` replicas even though there is only `1` replica of `kedify-scale-leader`.   

Other objects:

```
 kubectl describe scaledobjects.keda.sh -n observability otel-example
Name:         otel-example
Namespace:    observability
Labels:       scaledobject.keda.sh/name=otel-example
Annotations:  <none>
API Version:  keda.sh/v1alpha1
Kind:         ScaledObject
Metadata:
  Creation Timestamp:  2025-01-10T21:32:41Z
  Finalizers:
    finalizer.keda.sh
  Generation:        1
  Resource Version:  286279314
  UID:               ca86a917-e87c-483a-a65b-9c87144cb6c8
Spec:
  Max Replica Count:  10
  Min Replica Count:  0
  Scale Target Ref:
    Name:  kedify-scale-follower
  Triggers:
    Metadata:
      Clamp Max:            10
      Clamp Min:            0
      Metric Query:         kube_deployment_status_replicas_available{k8s_namespace_name="observability", k8s_deployment_name="kedify-scale-leader"}
      Operation Over Time:  last_one
      Scaler Address:       keda-otel-scaler.observability.svc:4318
      Target Value:         1
    Type:                   external
Status:
  Conditions:
    Message:  ScaledObject is defined correctly and is ready for scaling
    Reason:   ScaledObjectReady
    Status:   True
    Type:     Ready
    Message:  Scaling is performed because triggers are active
    Reason:   ScalerActive
    Status:   True
    Type:     Active
    Message:  No fallbacks are active on this scaled object
    Reason:   NoFallbackFound
    Status:   False
    Type:     Fallback
    Status:   Unknown
    Type:     Paused
  External Metric Names:
    s0-observability-otel-example
  Health:
    s0-observability-otel-example:
      Number Of Failures:  0
      Status:              Happy
  Hpa Name:                keda-hpa-otel-example
  Last Active Time:        2025-01-10T21:40:42Z
  Original Replica Count:  1
  Scale Target GVKR:
    Group:            apps
    Kind:             Deployment
    Resource:         deployments
    Version:          v1
  Scale Target Kind:  apps/v1.Deployment
Events:
  Type    Reason              Age    From           Message
  ----    ------              ----   ----           -------
  Normal  KEDAScalersStarted  8m20s  keda-operator  Scaler external is built.
  Normal  KEDAScalersStarted  8m20s  keda-operator  Started scalers watch
  Normal  ScaledObjectReady   8m20s  keda-operator  ScaledObject is ready for scaling

```

```
 kubectl get -n observability hpa -o yaml keda-hpa-otel-example
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2025-01-10T21:32:42Z"
  labels:
    app.kubernetes.io/managed-by: keda-operator
    app.kubernetes.io/name: keda-hpa-otel-example
    app.kubernetes.io/part-of: otel-example
    app.kubernetes.io/version: 2.14.0
    scaledobject.keda.sh/name: otel-example
  name: keda-hpa-otel-example
  namespace: observability
  ownerReferences:
  - apiVersion: keda.sh/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ScaledObject
    name: otel-example
    uid: ca86a917-e87c-483a-a65b-9c87144cb6c8
  resourceVersion: "286275315"
  uid: 13cc7e2e-f1b1-430e-9d2c-399c0e98aeec
spec:
  maxReplicas: 10
  metrics:
  - external:
      metric:
        name: s0-observability-otel-example
        selector:
          matchLabels:
            scaledobject.keda.sh/name: otel-example
      target:
        averageValue: "1"
        type: AverageValue
    type: External
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kedify-scale-follower
status:
  conditions:
  - lastTransitionTime: "2025-01-10T21:32:57Z"
    message: recommended size matches current size
    reason: ReadyForNewScale
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2025-01-10T21:32:57Z"
    message: 'the HPA was able to successfully calculate a replica count from external
      metric s0-observability-otel-example(&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name:
      otel-example,},MatchExpressions:[]LabelSelectorRequirement{},})'
    reason: ValidMetricFound
    status: "True"
    type: ScalingActive
  - lastTransitionTime: "2025-01-10T21:33:27Z"
    message: the desired count is within the acceptable range
    reason: DesiredWithinRange
    status: "False"
    type: ScalingLimited
  currentMetrics:
  - external:
      current:
        averageValue: "1"
      metric:
        name: s0-observability-otel-example
        selector:
          matchLabels:
            scaledobject.keda.sh/name: otel-example
    type: External
  currentReplicas: 10
  desiredReplicas: 10
  lastScaleTime: "2025-01-10T21:33:27Z"

```

Here are the metrics when I port forward to the otel-add-on service and hit the metrics endpoint:

```
 curl http://localhost:8080/metrics | grep keda_otel_scaler_metric_value
# HELP keda_otel_scaler_metric_value Last value of the metric that was read by the scaler.
# TYPE keda_otel_scaler_metric_value gauge
keda_otel_scaler_metric_value{aggregation="sum",labels="map[k8s_deployment_name:`kedify-scale-leader` k8s_namespace_name:`observability`]",name="kube_deployment_status_replicas_available",timeOp="avg"} 123
keda_otel_scaler_metric_value{aggregation="sum",labels="map[k8s_deployment_name:`kedify-scale-leader` k8s_namespace_name:`observability`]",name="kube_deployment_status_replicas_available",timeOp="last_one"} 123
keda_otel_scaler_metric_value{aggregation="sum",labels="map[k8s_deployment_name:kedify-scale-leader k8s_namespace_name:observability]",name="kube_deployment_status_replicas_available",timeOp="last_one"} 122
# HELP keda_otel_scaler_metric_value_clamped Last value of the metric that was read by the scaler within clampMin and clampMax bounds
# TYPE keda_otel_scaler_metric_value_clamped gauge
keda_otel_scaler_metric_value_clamped{aggregation="sum",labels="map[k8s_deployment_name:kedify-scale-leader k8s_namespace_name:observability]",name="kube_deployment_status_replicas_available",namespace="observability",scaledObject="otel-example",timeOp="last_one"} 10

```

Am I doing something wrong or is it just not working?  I love the idea of this addon but it is not working for me at the moment.

**Comment by jkremser** [comment]
hello @jhuizingh and thanks for trying the KEDA OTEL addon

> I tried type: kedify-otel but there was an error that it was an unknown type.

This works only when using the addon with Kedify agent `type == external` together with specifying `metadata.scalerAddress` should work, though.

I _think_, you are witnessing a situation where the `kube_deployment_status_replicas_available` metric has many dimensions (/labels) and when you specify those two:
- `k8s_namespace_name="observability"`
- `k8s_deployment_name="kedify-scale-leader"`
There are still more labels that were not filled and in this situation the default operation (sum) is applied to all the partially matching metrics.

Imagine following metrics:
```
kube_deployment_status_replicas_available{k8s_namespace_name=observability,k8s_deployment_name=kedify-scale-leader,foo=blue} 21
kube_deployment_status_replicas_available{k8s_namespace_name=observability,k8s_deployment_name=kedify-scale-leader,foo=green} 21
```

then query `kube_deployment_status_replicas_available{k8s_namespace_name="observability", k8s_deployment_name="kedify-scale-leader"}` will be returning `42`

I will try to replicate the issue and get back to you.

**Comment by jhuizingh** [comment]
@jkremser thanks for the response.

You are correct that there are other labels on this metric. However, just the label `k8s_deployment_name="kedify-scale-leader"` is enough to give a single time series for that metric. There is only one single deployment in the cluster with that name in the cluster. If I run that query in Grafana against my mimir backend, it gives me a single line at a steady level of 1.

If I do a sum of `kube_deployment_status_replicas_available` without any labels, it gives me the result 122 which is the count of all pods created by deployments in the cluster.

So for whatever reason, it seems like this tool is not using the labels at all.

**Comment by jkremser** [comment]
I think, I've replicated your state, here is what I've done:

```
helm upgrade -i keda kedacore/keda --namespace keda --create-namespace

helm upgrade -i -n observability ksm prometheus-community/kube-state-metrics --create-namespace

cat <<VALUES | helm upgrade -i kedify-otel oci://ghcr.io/kedify/charts/otel-add-on --version=v0.0.5 -f -
opentelemetry-collector:
  clusterRole:
    create: true
    rules:
     - apiGroups:
       - 'apps'
       resources:
       - 'replicasets'
       verbs:
       - 'get'
       - 'list'
       - 'watch'
     - apiGroups:
       - ''
       resources:
       - 'pods'
       verbs:
       - 'get'
       - 'list'
       - 'watch'
  alternateConfig:
    receivers:
      prometheus/kube_state_metrics:
        config:
          scrape_configs:
            - job_name: kube-state-metrics
              scrape_interval: 30s
              static_configs:
                - targets:
                    - ksm-kube-state-metrics.observability.svc:8080
    processors:
      k8sattributes/kube_state_metrics:
        pod_association:
          - sources:
            - from: resource_attribute
              name: k8s.pod.uid
          - sources:
            - from: resource_attribute
              name: k8s.pod.name
            - from: resource_attribute
              name: k8s.namespace.name
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.deployment.name
            - k8s.statefulset.name
            - k8s.daemonset.name
            - k8s.cronjob.name
            - k8s.job.name
            - k8s.node.name
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.pod.start_time
      groupbyattrs:
        keys:
          - k8s.pod.name
          - k8s.namespace.name
    service:
      pipelines:
        metrics:
          receivers: [prometheus/kube_state_metrics]
          processors: [k8sattributes/kube_state_metrics, groupbyattrs]
VALUES
```

 - then applied those two deployments and scaled object

And the `kedify-scale-follower` deployment was in fact scaled to maxReplicas (`10`) so same stuff as you've seen.

Here is how I debugged this:

otel-addon has a simple REST api that can help you inspect the in-memory storage as well as run the metric queries against it:

```
# 8080 is metrics endpoint, 9090 is GIN w/ REST that also has Swagger docs running
(k port-forward svc/keda-otel-scaler 9090)$

# test the existing metric query
curl -X 'POST' \
  'http://localhost:9090/memstore/query' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "operationOverTime": "last_one",
  "query": "kube_deployment_status_replicas_available{k8s_deployment_name=kedify-scale-leader,k8s_namespace_name=observability}"
}'
{
    "ok": true,
    "operation": "query",
    "error": "",
    "value": 18
}%

# 18 ... not good

# check the data if the labels are stored there correctly:
curl -X 'GET' \
  'http://localhost:9090/memstore/data' \
  -H 'accept: application/json' | jq '.kube_deployment_status_replicas_available[].labels'
{
  "deployment": "keda-operator",
  "namespace": "keda"
}
{
  "deployment": "metrics-server",
  "namespace": "kube-system"
}
{
  "deployment": "otel-add-on-scaler",
  "namespace": "default"
}
{
  "deployment": "local-path-provisioner",
  "namespace": "kube-system"
}
{
  "deployment": "keda-admission-webhooks",
  "namespace": "keda"
}
{
  "deployment": "keda-add-ons-http-external-scaler",
  "namespace": "keda"
}
{
  "deployment": "traefik",
  "namespace": "kube-system"
}
{
  "deployment": "keda-add-ons-http-interceptor",
  "namespace": "keda"
}
{
  "deployment": "ksm-kube-state-metrics",
  "namespace": "observability"
}
{
  "deployment": "coredns",
  "namespace": "kube-system"
}
{
  "deployment": "kedify-scale-leader",
  "namespace": "observability"
}
{
  "deployment": "kedify-scale-follower",
  "namespace": "observability"
}
{
  "deployment": "kedify-agent",
  "namespace": "keda"
}
{
  "deployment": "otelcol",
  "namespace": "default"
}
{
  "deployment": "keda-operator-metrics-apiserver",
  "namespace": "keda"
}

# ah cool, so the labels are called deployment and namespace and not k8s_{deployment,namespace}_name
```

So when you change the query to this, it does the trick (at least for me):
```
...
        metricQuery: kube_deployment_status_replicas_available{namespace="observability", deployment="kedify-scale-leader"}
...
```

Why it has different labels compared to the grafana? I don't know to be honest, it might be related to the processors you've used in the values for OTEL collector or the internal (scoped-based) model of metrics OTEL [uses](https://opentelemetry.io/docs/specs/otel/metrics/data-model/). tbh, `¯\_(ツ)_/¯` what can also help is using the debug log output in the otel collector and check the metric's dimensions there.

pls, let me know if that fixes your issue.

**Comment by jkremser** [comment]
btw, if you want to see the things working quickly, override the default config for HPA by adding something this to the ScaledObject:

```
...
  # under .spec
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 10
        scaleUp:
          stabilizationWindowSeconds: 10
```
